### ISSUE TITLE
PhenoTagger Demo at Hugging Face not working

### ISSUE THREAD

**Issue by azankl** [ncbi-nlp/PhenoTagger#11]
I get a runtime error (full error message below).

Runtime error
Traceback (most recent call last):
  File "/home/user/.local/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/home/user/.local/lib/python3.7/site-packages/streamlit/__init__.py", line 70, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/user/.local/lib/python3.7/site-packages/streamlit/delta_generator.py", line 90, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/home/user/.local/lib/python3.7/site-packages/streamlit/elements/arrow_altair.py", line 27, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'
Container logs:

===== Application Startup at 2023-07-25 06:09:10 =====

Traceback (most recent call last):
  File "/home/user/.local/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/home/user/.local/lib/python3.7/site-packages/streamlit/__init__.py", line 70, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/user/.local/lib/python3.7/site-packages/streamlit/delta_generator.py", line 90, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/home/user/.local/lib/python3.7/site-packages/streamlit/elements/arrow_altair.py", line 27, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'

**Comment by lingluodlut** [comment]
Thanks for your reminder. It is caused by the altair's version. I have fixed it. Now it works. @azankl
